### ISSUE TITLE
Panic when running the application for the first time

### ISSUE THREAD

**Issue by Shrinidhi-P-ML** [maplelabs/opensearch-scaling-manager#105]
```
time="2022-12-16T00:00:05Z" level=info msg="Index already exists type=provisioner.info"
00:05:00
Fri Dec 16 00:05:00 UTC 2022
time="2022-12-16T00:05:00Z" level=info msg="Index create Response: [200 OK] {\"acknowledged\":true,\"shards_acknowledged\":true,\"index\":\"monitor-stats-1\"}"
time="2022-12-16T00:05:00Z" level=info msg="Get resp: [404 Not Found] {\"_index\":\"monitor-stats-1\",\"_id\":\"412531800\",\"found\":false}  type=provisioner.info"
time="2022-12-16T00:05:01Z" level=info msg="Update resp: [201 Created] {\"_index\":\"monitor-stats-1\",\"_id\":\"412531800\",\"_version\":1,\"result\":\"created\",\"_shards\":{\"total\":2,\"successful\":1,\"failed\":0},\"_seq_no\":0,\"_primary_term\":1}  type=provisioner.info"
panic: interface conversion: interface {} is nil, not map[string]interface {}
 
goroutine 1 [running]:
scaling_manager/provision.(*State).GetCurrentState(0xc00043e080)
        /home/ubuntu/time_testing/opensearch-scaling-manager/provision/state_functions.go:124 +0x5ac
main.main()
        /home/ubuntu/time_testing/opensearch-scaling-manager/main.go:19 +0x35
exit status 2
```

**Comment by Meghana-R-ML** [comment]
Fixed by #106
